### ISSUE TITLE
crash during listpeers call

### ISSUE THREAD

**Issue by vincenzopalazzo** [LNOpenMetrics/go-lnmetrics.reporter#105]
In the master, we are running now the `listpeers` call, and it is broken with the following stacktrace

```
panic: json: cannot unmarshal number 18446744073709552000 into Go struct field PeerChannel.PeerSnapshot.channels.max_htlc_value_in_flight_msat of type uint64

goroutine 10 [running]:
main.onInit(0xc00011fdc8?, 0xc00019a1e0?, 0xc00007ca00)
	/home/vincent/github/go-metrics-reported/cmd/go-lnmetrics.reporter/main.go:90 +0x436
github.com/vincenzopalazzo/glightning/glightning.InitMethod.Call({{0xc0000302c0, 0xa8, 0xb0}, 0xc00007ca00, 0xc000180cb0})
	/home/vincent/github/go-metrics-reported/vendor/github.com/vincenzopalazzo/glightning/glightning/plugin.go:1127 +0x325
github.com/vincenzopalazzo/glightning/jrpc2.Execute(0xc000012348, {0x80db98?, 0xc00019a030?})
	/home/vincent/github/go-metrics-reported/vendor/github.com/vincenzopalazzo/glightning/jrpc2/server.go:196 +0x30
github.com/vincenzopalazzo/glightning/jrpc2.processMsg(0xc000070a00, {0xc000192000, 0x253, 0x253})
	/home/vincent/github/go-metrics-reported/vendor/github.com/vincenzopalazzo/glightning/jrpc2/server.go:192 +0x16a
created by github.com/vincenzopalazzo/glightning/jrpc2.(*Server).listen
	/home/vincent/github/go-metrics-reported/vendor/github.com/vincenzopalazzo/glightning/jrpc2/server.go:120 +0xe5

```

**Comment by vincenzopalazzo** [comment]
Introduced in https://github.com/LNOpenMetrics/go-lnmetrics.reporter/pull/103
