### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vincenzopalazzo** [LNOpenMetrics/go-lnmetrics.reporter#110]
This need to be investigated, this is the current stack trace

```
➜  VincentSSD panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6c320c]

goroutine 118 [running]:
github.com/vincenzopalazzo/cln4go/client.(*UnixRPC).decodeToResponse(0xc0000dfbc0, {0xc0002c2000, 0x8ec0, 0xa000})
	/home/vincent/go/pkg/mod/github.com/vincenzopalazzo/cln4go/client@v0.0.0-20221029082447-17087277873c/unix.go:51 +0xcc
github.com/vincenzopalazzo/cln4go/client.UnixRPC.Call({{0x805e88, 0xc0000ba250}, {0x0, 0x0}, {0x804840, 0xa18568}}, {0x772d6c, 0x9}, 0xc00052a270)
	/home/vincent/go/pkg/mod/github.com/vincenzopalazzo/cln4go/client@v0.0.0-20221029082447-17087277873c/unix.go:91 +0x2e9
github.com/vincenzopalazzo/cln4go/client.Call[...]({0x801460, 0xc00015a360}, {0x772d6c, 0x9}, {0x46d365})
	/home/vincent/go/pkg/mod/github.com/vincenzopalazzo/cln4go/client@v0.0.0-20221029082447-17087277873c/client.go:14 +0x70
github.com/LNOpenMetrics/go-lnmetrics.reporter/pkg/ln.ListPeers({0x801460?, 0xc00015a360?}, 0x4f0306?)
	/home/vincent/Github/lnmetrics/go-lnmetrics.reporter/pkg/ln/client.go:88 +0x3f
github.com/LNOpenMetrics/go-lnmetrics.reporter/internal/plugin.(*MetricOne).snapshotListPeers(0xc0001600e0, {0x801460, 0xc00015a360})
	/home/vincent/Github/lnmetrics/go-lnmetrics.reporter/internal/plugin/metrics_one.go:88 +0x7c
github.com/LNOpenMetrics/go-lnmetrics.reporter/internal/plugin.(*MetricOne).onEvent(0x46d365?, {0x772dc6, 0x9}, {0x801460, 0xc00015a360})
	/home/vincent/Github/lnmetrics/go-lnmetrics.reporter/internal/plugin/metrics_one.go:106 +0x59
github.com/LNOpenMetrics/go-lnmetrics.reporter/internal/plugin.(*MetricOne).Update(0xc0001600e0, {0x801460?, 0xc00015a360?})
	/home/vincent/Github/lnmetrics/go-lnmetrics.reporter/internal/plugin/metrics_one.go:209 +0x45
github.com/LNOpenMetrics/go-lnmetrics.reporter/internal/plugin.(*MetricsPlugin).callUpdateOnMetricNoMsg(0x9e8320, {0x806058, 0xc0001600e0})
	/home/vincent/Github/lnmetrics/go-lnmetrics.reporter/internal/plugin/plugin.go:101 +0x86
github.com/LNOpenMetrics/go-lnmetrics.reporter/internal/plugin.(*MetricsPlugin).updateAndUploadMetric(0x9e8320, {0x806058, 0xc0001600e0})
	/home/vincent/Github/lnmetrics/go-lnmetrics.reporter/internal/plugin/plugin.go:109 +0x7a
created by github.com/LNOpenMetrics/go-lnmetrics.reporter/internal/plugin.(*MetricsPlugin).RegisterRecurrentEvt.func1
	/home/vincent/Github/lnmetrics/go-lnmetrics.reporter/internal/plugin/plugin.go:123 +0xac

```

**Comment by vincenzopalazzo** [comment]
Looks like related to https://github.com/vincenzopalazzo/cln4go/issues/49
