### ISSUE TITLE
EOF panic while running

### ISSUE THREAD

**Issue by vincenzopalazzo** [LNOpenMetrics/go-lnmetrics.reporter#119]
This is  some log that I was able to extract from the crash

```
time="2022-11-23T03:53:37+01:00" level=info msg="Hash of the paylad: e72bba0979e327e7839e3b7e575cec5fb8b945df6f22a9a89c7681114e11cd81"
time="2022-11-23T03:53:37+01:00" level=info msg="cln4go: read chunk"
time="2022-11-23T03:53:37+01:00" level=info msg="cln4go: reading 313"
time="2022-11-23T03:53:37+01:00" level=info msg="cln4go: buffer pre dencoding {\"jsonrpc\":\"2.0\",\"id\":\"3645\",\"result\":{\"signature\":\"3a437f1081528c93b72183f244a917ea67b93792d7263f7a9a5cb776c8689f4a1d8b2c317d5339cb1f82eebb9eef683db94cc762eaa91fab09e4feef2daf73ee\",\"recid\":\"00\",\"zbase\":\"dh7rg9aoofje3r7zrgb9rtfjn9igxqjz1mm1cx54ujqmq7sepnxww8cmfoaz4w333cxaf5i5u5zsoxp3judsf4ijd6iou3867hs46h9q\"}}\n\n"
time="2022-11-23T03:53:37+01:00" level=info msg="Call updateMetricOne"
time="2022-11-23T03:53:37+01:00" level=error msg="Error All the request to push the data into request are failed. 0 Failure over 0 request: "
time="2022-11-23T03:53:37+01:00" level=error msg="Error All the request to push the data into request are failed. 0 Failure over 0 request"
time="2022-11-23T04:20:40+01:00" level=error msg="run time panic: EOF"
time="2022-11-23T04:20:40+01:00" level=error msg="stacktrace goroutine 1 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\nmain.main.func1()\n\t/home/vincent/Github/lnmetrics/go-lnmetrics.reporter/cmd/go-lnmetrics.reporter/main.go:17 +0x6a\npanic({0x7886e0, 0xc000024140})\n\t/usr/local/go/src/runtime/panic.go:884 +0x212\ngithub.com/vincenzopalazzo/cln4go/plugin.(*Plugin[...]).Start(0xc0001822a0)\n\t/home/vincent/Github/lnmetrics/go-lnmetrics.reporter/vendor/github.com/vincenzopalazzo/cln4go/plugin/plugin.go:190 +0x9e5\nmain.main()\n\t/home/vincent/Github/lnmetrics/go-lnmetrics.reporter/cmd/go-lnmetrics.reporter/main.go:35 +0xec\n"
```

I think this is related to cln4go

**Comment by vincenzopalazzo** [comment]
Should be fixed in https://github.com/vincenzopalazzo/cln4go/releases/tag/v0.0.1-beta.7
