### ISSUE TITLE
plugin: Crash report

### ISSUE THREAD

**Issue by vincenzopalazzo** [LNOpenMetrics/go-lnmetrics.reporter#69]
```
INFO    plugin-paytest.py: RPC method 'testinvoice' does not have a docstring.
INFO    plugin-paytest.py: RPC method 'paytest' does not have a docstring.
INFO    connectd: Static Tor service onion address: "beatifulnewonionaddresskindofrandombutrequiresfantasyyes.onion:9735,127.0.0.1:9735" bound from extern port 9735 
INFO    plugin-bcli: bitcoin-cli initialized and connected to bitcoind.
INFO    plugin-autoclean: autocleaning every 3600 seconds
INFO    lightningd: --------------------------------------------------
INFO    lightningd: Server started with public key 755746d3291fae3fa45461c990d4882470a04c0cf730ae8032c19fdf363d787e05, alias HAPPYGIRAFFE-v0.10.2-94-g5a5cf8c (color #a5cf8c) and lightningd v0.10.2-94-g5a5cf8c
panic: leveldb: not found

goroutine 23 [running]:
main.onInit(0xc000114930, 0xc00009b770, 0xc0000c4370)
	/root/go-lnmetrics.reporter/cmd/go-lnmetrics.reporter/main.go:90 +0x813
github.com/vincenzopalazzo/glightning/glightning.InitMethod.Call(0xc0000dc240, 0x35, 0x40, 0xc0000c4370, 0xc000114930, 0x40eb5b, 0xc0000a8318, 0x18, 0x18)
	/root/go/pkg/mod/github.com/vincenzopalazzo/glightning@v0.8.3-0.20211027092546-52b0b2cd4373/glightning/plugin.go:1127 +0x2a7
github.com/vincenzopalazzo/glightning/jrpc2.Execute(0xc0000a8330, 0x83e680, 0xc00009b5c0, 0x83e680)
	/root/go/pkg/mod/github.com/vincenzopalazzo/glightning@v0.8.3-0.20211027092546-52b0b2cd4373/jrpc2/server.go:196 +0x35
github.com/vincenzopalazzo/glightning/jrpc2.processMsg(0xc0000e4440, 0xc00012a000, 0x1b7, 0x1b7)
	/root/go/pkg/mod/github.com/vincenzopalazzo/glightning@v0.8.3-0.20211027092546-52b0b2cd4373/jrpc2/server.go:192 +0x191
created by github.com/vincenzopalazzo/glightning/jrpc2.(*Server).listen
	/root/go/pkg/mod/github.com/vincenzopalazzo/glightning@v0.8.3-0.20211027092546-52b0b2cd4373/jrpc2/server.go:120 +0x18a
INFO    plugin-go-lnmetrics: Killing plugin: exited before replying to init
INFO    plugin-summary.py: Plugin summary.py initialized
```

Reported by @jsarenik

**Comment by jsarenik** [comment]
Yes, works well now. Thank you.
